version: '3'

services:
  broker:
    image: 'bitnami/kafka:3.3.2'
    networks:
      - net
    volumes:
      - kafkadata:/bitnami/kafka
    environment:
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093, EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: kafka-topics.sh --bootstrap-server broker:9092 --topic hc --create --if-not-exists && kafka-topics.sh --bootstrap-server broker:9092 --topic hc --describe
      interval: 1s
      timeout: 60s
      retries: 60
    ports:
      - 9094:9094
  
  

volumes:
  kafkadata:

networks:
  net:
    driver: bridge